YEAR_EXPERTISE_GAIN = {"1st year": 0, "2nd year": 1, "3rd year": 2, "4th year":3 , "Masters": 4, "PhD":6}
EXPERIENCE_LEVEL_VALUE = {"Beginner":0, "Intermediate":1, "Advanced":2}

PROGRAMMING_SKILLS_VALUES = {
    
    'react': 5,
    'data analysis': 4,
    'rust': 1,
    'figma': 5,
    'react native': 5,
    'c++': 2,
    'css': 5,
    'ios': 3,
    'html': 5,
'aws/azure/gcp': 3, 
'tensorflow': 4, 
'go': 2, 
'design': 4, 
'blockchain': 2,
 'computer vision': 4,
   'flask': 4, 
   'java': 3, 
   'javascript': 5, 
   'github': 5, 
   'data visualization': 4,
     'android development': 2,
       'mongodb': 3, 'aws': 2, 
       'ui/ux design': 5,
         'natural language processing': 3,
           'typescript': 4, 
           'sql': 4, 
           'docker': 3, 
           'iot': 3, 
           'pytorch': 4, 
           'flutter': 4, 
           'postgresql': 3, 
           'python': 5, 
           'machine learning': 4, 
           'ml': 4, 
           'agile methodology': 1, 
           'git': 5, 
           'html/css': 5, 
           'java script': 5, 
           'data analysis': 4, 
           'rust ': 2, 
           'pytorch ': 4, 
           'agile': 1,
 "android": 3,
}
