YEAR_EXPERTISE_GAIN = {"1st year": 0, "2nd year": 1, "3rd year": 2, "4th year":3 , "Masters": 4, "PhD":6}
EXPERIENCE_LEVEL_VALUE = {"Beginner":0, "Intermediate":1, "Advanced":2}

PROGRAMMING_SKILLS_VALUES = {
    'React': 5,
    'data analysis': 4,
    'Rust': 1,
    'Figma': 5,
    'React Native': 5,
    'C++': 2,
    'CSS': 5,
    'iOS Development': 3,
    'HTML': 5,
    'AWS/Azure/GCP': 3,
    'TensorFlow': 4,
    'Go': 2,
    'Design': 4,
    'Blockchain': 2,
    'Computer Vision': 4,
    'Flask': 4,
    'Java': 3,
    'JavaScript': 5,
    'GitHub': 5,
    'Data Visualization': 4,
    'Android Development': 2,
    'MongoDB': 3,
    'AWS': 2,
    'UI/UX Design': 5,
    'Natural Language Processing': 3,
    'TypeScript': 4,
    'SQL': 4,
    'Docker': 3,
    'IoT': 3,
    'PyTorch': 4,
    'Flutter': 4,
    'PostgreSQL': 3,
    'Python': 5,
    'Machine Learning': 4,
    'ML': 4,
    'Agile Methodology': 1,
    'Git': 5,
    'HTML/CSS': 5,
    'java script': 5,
    'Data Analysis': 4,
    'Rust ': 2,
    'PyTorch ': 4,
    'Agile': 1,
    'PostgreSQL': 3
}
